spring:
  config:
    profiles:
      group:
        dev: env-dev

---
spring:
  config:
    activate:
      on-profile: env-dev
  redis:
    host: localhost
    port: 6879

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: golf
    password: 1234
    url:
    hikari:
      maximum-pool-size: 100

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessToken-validity-in-seconds: 3600 # 1시간
  refreshToken-validity-in-seconds: 18000 # 5시간