spring:
  config:
    profiles:
      group:
        prd: env-prd

---
spring:
  config:
    activate:
      on-profile: env-prd
  redis:
    host: localhost
    port: 6879

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: golf
    password: 1234
    url:
    hikari:
      maximum-pool-size: 100

  jpa:
    open-in-view: false

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessToken-validity-in-seconds: 3600 # 1??
  refreshToken-validity-in-seconds: 18000 # 5??

